services:
  # PostgreSQL Database
  - type: pserv
    name: securecrop-db
    env: docker
    plan: free
    region: oregon
    
  # Django Web Service
  - type: web
    name: securecrop-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn -c gunicorn.conf.py securecrop.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: securecrop-db
          property: connectionString
      - key: ALLOWED_HOSTS
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: INFOBIP_API_KEY
        sync: false
      - key: INFOBIP_BASE_URL
        sync: false
      - key: INFOBIP_SENDER
        sync: false
      - key: GEMINI_API_KEY
        sync: false

databases:
  - name: securecrop-db
    plan: free
    region: oregon
